export enum ErrorCode {
  // Auth
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  FIRST_LOGIN_REQUIRED = 'FIRST_LOGIN_REQUIRED',
  TWO_FA_REQUIRED = 'TWO_FA_REQUIRED',
  TWO_FA_INVALID = 'TWO_FA_INVALID',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  // Shop
  SHOP_NOT_FOUND = 'SHOP_NOT_FOUND',
  SHOP_INVALID_KEY = 'SHOP_INVALID_KEY',
  SHOP_INACTIVE = 'SHOP_INACTIVE',
  SHOP_ALREADY_EXISTS = 'SHOP_ALREADY_EXISTS',

  // Shop Group
  SHOP_GROUP_NOT_FOUND = 'SHOP_GROUP_NOT_FOUND',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_INACTIVE = 'USER_INACTIVE',
  USER_BANNED = 'USER_BANNED',

  // Balance
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',

  // OTP
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DUPLICATE_REQUEST = 'DUPLICATE_REQUEST',
}
